version: '3.7'

# On linux make sure you have set DOCKER_HOST_IP=172.17.0.1
# Get the correct IP address from docker0 interface by executing: ifconfig

services:

  # https://hub.docker.com/r/confluentinc/cp-kafka/
  kafka:
    
    hostname: kafka
    image: confluentinc/cp-kafka:5.5.3
    # Just in case Zookeeper isn't up yet
    #restart: always
    environment:
      # The KAFKA_ADVERTISED_LISTENERS variable is set to kafka:9092. This will make Kafka accessible to other
      # containers by advertising it’s location on the Docker network.
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:19092,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      # The same ZooKeeper port is specified here as the previous container.
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      # The KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR is set to 1 for a single-node cluster. Unless you have three or more
      # nodes you do not need to change this from the default.
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_NUM_PARTITIONS: 4
      JMX_PORT: 9999
      KAFKA_JMX_OPTS: -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=kafka -Dcom.sun.management.jmxremote.rmi.port=9999
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      CONFLUENT_SUPPORT_CUSTOMER_ID: 'anonymous'
      KAFKA_SCHEMA_REGISTRY_URL: "schemaregistry:8081"
    ports:
    - 9092:9092
    - 9998:9999
    depends_on:
    - zookeeper

  # https://hub.docker.com/r/confluentinc/cp-zookeeper/
  zookeeper:
    
    image: confluentinc/cp-zookeeper:5.5.3
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - 2181:2181

  # https://hub.docker.com/r/confluentinc/cp-schema-registry/
  schema-registry:
    image: confluentinc/cp-schema-registry:5.5.3
    hostname: schema-registry
   
    depends_on:
      - zookeeper
      - kafka
    ports:
      - 8081:8081
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: "zookeeper:2181"
      SCHEMA_REGISTRY_HOST_NAME: schemaregistry
      SCHEMA_REGISTRY_LISTENERS: "http://0.0.0.0:8081"
   
  kafka-rest:
    image: confluentinc/cp-kafka-rest:5.5.3
    hostname: kafka-rest
    ports:
    - "38082:38082"
    depends_on:
      - schema-registry
    environment:
      KAFKA_REST_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_REST_SCHEMA_REGISTRY_URL: schema-registry:8081
      KAFKA_REST_HOST_NAME: kafka-rest
      KAFKA_REST_LISTENERS: http://kafka-rest:38082

  # https://hub.docker.com/r/hlebalbau/kafka-manager/
  # Kafka Manager: http://localhost:9000
  #kafka-manager:
  #  
  #  image: hlebalbau/kafka-manager
  #  environment:
  #    ZK_HOSTS: "zookeeper:2181"
  #  ports:
  #  - 9000:9000
  #  depends_on:
  #  - kafka
#
  #kafdrop:
  #  image: obsidiandynamics/kafdrop
  #  ports:
  #    - 9100:9000
  #  environment:
  #    - KAFKA_BROKERCONNECT=kafka:19092
  #    - JVM_OPTS=-Xms32M -Xmx64M
  #  depends_on:
  #    - kafka

  akhq:
    # build:
    #   context: .
    image: tchiotludo/akhq
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            docker-kafka-server:
              properties:
                bootstrap.servers: "kafka:19092"
              schema-registry:
                url: "http://schema-registry:8081"

    ports:
      - 9080:8080
    links:
      - kafka
      - schema-registry